package org.example.Model.Enums;

public enum Genre {
    ACTION_ADVENTURE, SCIENCE_FICTION, FANTASY, MYSTERY, ROMANCE, THRILLER, HISTORICAL_FICTION, BIOGRAPHY_MEMOIR, SELF_HELP,
    SCIENCE, HISTORY, DRAMA, COMEDY, HORROR, DOCUMENTARY, LITERATURE, FASHION, NEWS, OTHER
}
